apiVersion: v1
kind: Service
metadata:
  name: vihotask-backend
  namespace: vahiztech
  labels:
    app.kubernetes.io/name: vihotask-backend
    app.kubernetes.io/part-of: vihotask
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app.kubernetes.io/name: vihotask-backend
