apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vahiztech

resources:
  - namespace.yaml
  - postgres/postgres-service.yaml
  - postgres/postgres-statefulset.yaml
  - keycloak/keycloak-service.yaml
  - keycloak/keycloak-deployment.yaml
  - coursedemy/coursedemy-backend-service.yaml
  - coursedemy/coursedemy-backend-deployment.yaml
  - coursedemy/coursedemy-frontend-service.yaml
  - coursedemy/coursedemy-frontend-deployment.yaml
  - vihotask/vihotask-backend-service.yaml
  - vihotask/vihotask-backend-deployment.yaml
  - ingress.yaml
