apiVersion: v1
kind: Secret
metadata:
  name: vahiztech-secrets
  namespace: vahiztech
type: Opaque
stringData:
  # Database Credentials
  POSTGRES_USER: keycloak
  POSTGRES_PASSWORD: your_strong_postgres_password_here

  # Keycloak IAM Credentials
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: your_strong_admin_password_here

  # Microservices Application Secrets
  COURSEDEMY_JWT_SECRET: your_base64_jwt_secret_here
  COURSEDEMY_AUTH_SECRET: your_auth_secret_key_here
  VIHOTASK_JWT_SECRET: your_base64_jwt_secret_here
