apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vahiztech-dev

resources:
  - ../../base

# Ghi đè namespace cho môi trường dev
patches:
  - target:
      kind: Namespace
      name: vahiztech
    patch: |-
      - op: replace
        path: /metadata/name
        value: vahiztech-dev
